### ISSUE TITLE
WhoIS Errors out

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Plugins/Nettools#1]
Try to use whois and get a php error message on PHP 7.3

`E_WARNING(2) - implode(): Invalid arguments passed @ /public_html/nettools/whois.php line 77`

Also whois link displayed for ip in comments (to admins) doesn't work on Geeklog.net. This is a sample  link that is used: http://www.geeklog.net/nettools/whois.php?domain=68.148.26.220

**Comment by mystralkk** [comment]
As for errors caused by the improper use of the implode function, I fixed with change set 55ee1f3.

**Comment by mystralkk** [comment]
All right, I updated phpWhois library to v4.2.2 and changed some code.  Now I think I have fixed bugs.

**Comment by eSilverStrike** [comment]
Thanks, I will add it to Geeklog.net and confirm

**Comment by eSilverStrike** [comment]
Working now.
