### ISSUE TITLE
Update phpWhois

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Plugins/Nettools#2]
The NetTools plugin uses the modified version of phpWHois v4.2.2 , which causes an error with PHP 8.0.  The latest version of phpWhois is v4.2.5, but this version (and probably the version we are using) was reported to have a serious security issue as early as 2015.  phpWhois developers seem inactive and the project is almost abandoned.

One of the forked versions that seems to be most used is [jsmitty12/](https://packagist.org/packages/jsmitty12/)phpwhois, which requires at least PHP 7.0.  What should we do, @eSilverStrike ?

**Comment by eSilverStrike** [comment]
Well we can't have a security issue so I guess the jsmitty12 forked version would be the easiest root.

I guess we would then need to add PHP to the Dependencies check Geeklog does for the plugins so NetTools can specify PHP 7 or higher. Any plugin that doesn't specify a PHP dependency can be assumed the same as Geeklog.

**Comment by mystralkk** [comment]
Thanks for your advice, @eSilverStrike .  I used the latest library from jsmitty12/phpwhois, which requires at least PHP 7.2.0.  I tried older versions that require PHP 7.0.0, but they cause errors because of the libraries they depend on.
