### ISSUE TITLE
WhoIs query is not compatible with PHP 8.1

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Plugins/Nettools#3]
Got the following error when I submitted a whois query

( ! ) Fatal error: Array and string offset access syntax with curly braces is no longer supported in C:\wamp64\www\geeklogdev\public_html\nettools\whois.idna.php on line 377
--
1 | 0.0006 | 377664 | {main}( ) | ...\whois.php:0
2 | 0.0462 | 997976 | include_once( 'C:\wamp64\www\geeklogdev\public_html\nettools\whois.main.php ) | ...\whois.php:32

It looks like the library is at 6.0.0 and 6.0.2 is now available. Hopefully this update would fix this.
https://packagist.org/packages/jsmitty12/phpwhois#v6.0.2

@mystralkk I see you used composer to update it the last time. When you have time could you do this update? 

Should we include the composer files with the plugin so updates would be easier?

**Comment by mystralkk** [comment]
I am afraid you are using an older version of the Nettools plugin.  Currently, the PhpWhois library is located under the "private/plugins/nettools/vendor/jsmitty12/phpwhois/src/" directory, not under "public_html/nettools/".

Below is part of the "composer.lock" under "private/plugins/nettools/":
```JSON
        {
            "name": "jsmitty12/phpwhois",
            "version": "v6.0.2",
            "source": {
                "type": "git",
                "url": "https://github.com/jsmitty12/phpWhois.git",
                "reference": "4d56dfbc926f082d23259bc6243a7b3760f7f37a"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/jsmitty12/phpWhois/zipball/4d56dfbc926f082d23259bc6243a7b3760f7f37a",
                "reference": "4d56dfbc926f082d23259bc6243a7b3760f7f37a",
                "shasum": ""
            },
            "require": {
                "algo26-matthias/idna-convert": "^3.0",
                "php": ">=7.2"
            },
            "require-dev": {
                "dms/phpunit-arraysubset-asserts": "~0.1",
                "phpunit/phpunit": "^8.0 || ^9.0"
            },
            "suggest": {
                "lib-openssl": "*"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "phpWhois\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "GPL-2.0-or-later"
            ],
```

So, the current PhpWhoIs version we are using is 6.0.2, not 6.0.0.

**Comment by eSilverStrike** [comment]
You are right. I had been checking and testing a bunch of the plugins and missed updating this one to the latest version. Sorry about that. I had wondered why I couldn't find the composer files but had only looked at my local repository clone.
